name: Master App Build

on:
  push:
    branches:
    - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      # with:
      #   ref: master
      #   clean: 'true'
      #   token: '${{ secrets.GIT_TOKEN }}'
      #   submodules: 'recursive'
      #   fetch-depth: '0'        
    
    - name: Present Working Directory
      run: |
          pwd
          ls
   