name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: listing all directory
      run: |
          pwd
          ls
          echo ${{ github.run_id }}

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Build and push
    #   uses: docker/build-push-action@v3
    #   with:
    #     push: true
    #     tags: adminmindgrep/delivery:${{ github.run_id }}

    - name: Edit helm chart and push back to gitHub
      run: | 
          git clone https://rishabhmindgrep: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@github.com/Mindgreppers/delivery.git
          pwd
          ls -ltr
          cd delivery/
          ls
          cd helm-chart/
          ls
          NEW_TAG= {{ github.run_id }}
          # OLD_TAG=`grep "tag: " helm-chart/values.yaml | awk '{print $2}'`
          # sed -i "s/$OLD_TAG/$NEW_TAG/g" values.yaml
          # cat values.yaml
          





    # - id: 'auth'
    #   uses: 'google-github-actions/auth@v1'
    #   with:
    #     credentials_json: '${{ secrets.GCLOUD_AUTH_KEY }}'

    # - name: 'Set up Cloud SDK'
    #   uses: 'google-github-actions/setup-gcloud@v1'

    # - name: 'Use gcloud CLI'
    #   run: |
    #       gcloud info

    # - id: 'get-credentials'
    #   uses: 'google-github-actions/get-gke-credentials@v1'
    #   with:
    #     cluster_name: 'godspeed'
    #     location: 'us-central1-c'
    
    # - id: 'get-pods'
    #   run: |
    #       kubectl get pods -n app
    #       helm ls -n app
    #       cd helm-chart
    #       helm upgrade delivery . --set image.repository=adminmindgrep/delivery --set image.tag=${{ github.run_id }} -n app
    #       sleep 30
    #       kubectl get pods -n app
