name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: listing all directory
      run: |
          pwd
          ls
          echo ${{ github.run_id }}

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: adminmindgrep/orchestrator:${{ github.run_id }}

    - name: Deploy Helm chart 
      uses: hahow/install-helm-chart-action@v1
      with:
        gcloud_auth_key: ${{ secrets.GCLOUD_AUTH_KEY }}
        gcloud_project_id: high-keel-368610
        cluster_name: godspeed
        cluster_region: us-central1-c
        release_namespace: app
        release_name: payment-system
        chart_name: ./helm-chart/
        helm_upgrade_args: |
          --set image.tag=${{ github.sha }}