name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: listing all directory
      run: |
          pwd
          ls
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag mind-grep:$(date +%s)

    - name: Push Docker Images
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: adminmindgrep/mindgrep-delivery
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}