name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: listing all directory
      run: |
          pwd
          ls
          echo ${{ github.run_id }}

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Build and push
    #   uses: docker/build-push-action@v3
    #   with:
    #     push: true
    #     tags: adminmindgrep/delivery:${{ github.run_id }}

    # - name: Deploy Delivery App
    #   run: | 
    #       cd helm-chart
    #       gcloud container clusters get-credentials godspeed --zone us-central1-c --project high-keel-368610
    #       helm upgrade delivery --dry-run . --set image.repository=adminmindgrep/delivery --set image.tag=${{ github.run_id }}

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCLOUD_AUTH_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: |
          gcloud info

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v1'
      with:
        cluster_name: 'godspeed'
        location: 'us-central1-c'
        use_connect_gateway: 'true'

    # The KUBECONFIG env var is automatically exported and picked up by kubectl.
    - id: 'get-pods'
      run: 'kubectl get pods'